// 交易數據(主檔+明細)維護畫面的通用設定。
// itemNoField 為 null 時代表明細沒有獨立項次欄位(以其他鍵值識別)。
const DOCUMENT_TABLES = {
  // ---- SD 訂單模組 ----
  "sales-order": {
    headerTable: "客戶訂單主檔",
    headerPk: ["訂單編號"],
    headerFields: [
      { name: "訂單編號", label: "訂單編號", type: "text", required: true },
      { name: "訂單日期", label: "訂單日期", type: "date", required: true },
      { name: "銷售組織", label: "銷售組織", type: "select", refKey: "sales-org", required: true },
      { name: "客戶編號", label: "客戶編號", type: "select", refKey: "customer", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    detailTable: "客戶訂單明細",
    detailFk: ["訂單編號"],
    itemNoField: "訂單項次",
    detailFields: [
      { name: "物料編號", label: "物料編號", type: "select", refKey: "material", required: true },
      { name: "訂單數量", label: "訂單數量", type: "number", required: true },
      { name: "預定交期", label: "預定交期", type: "date" },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    readonlyDetailFields: [
      { name: "出貨數量", label: "已出貨" },
      { name: "退回數量", label: "已退回" },
    ],
  },
  shipment: {
    headerTable: "訂單出貨主檔",
    headerPk: ["出貨編號"],
    headerFields: [
      { name: "出貨編號", label: "出貨編號", type: "text", required: true },
      { name: "出貨日期", label: "出貨日期", type: "date", required: true },
      { name: "銷售組織", label: "銷售組織", type: "select", refKey: "sales-org", required: true },
      { name: "客戶編號", label: "客戶編號", type: "select", refKey: "customer", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    detailTable: "訂單出貨明細",
    detailFk: ["出貨編號"],
    itemNoField: "出貨項次",
    detailFields: [
      { name: "訂單編號", label: "訂單編號", type: "text", required: true },
      { name: "訂單項次", label: "訂單項次", type: "text", required: true },
      { name: "物料編號", label: "物料編號", type: "select", refKey: "material", required: true },
      { name: "倉庫代碼", label: "倉庫代碼", type: "select", refKey: "warehouse", required: true },
      { name: "出貨數量", label: "出貨數量", type: "number", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    sourceView: { key: "order-open", label: "已訂未出明細" },
  },
  "shipment-return": {
    headerTable: "出貨退回主檔",
    headerPk: ["退回編號"],
    headerFields: [
      { name: "退回編號", label: "退回編號", type: "text", required: true },
      { name: "退回日期", label: "退回日期", type: "date", required: true },
      { name: "銷售組織", label: "銷售組織", type: "select", refKey: "sales-org", required: true },
      { name: "客戶編號", label: "客戶編號", type: "select", refKey: "customer", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    detailTable: "出貨退回明細",
    detailFk: ["退回編號"],
    itemNoField: "退回項次",
    detailFields: [
      { name: "訂單編號", label: "訂單編號", type: "text", required: true },
      { name: "訂單項次", label: "訂單項次", type: "text", required: true },
      { name: "物料編號", label: "物料編號", type: "select", refKey: "material", required: true },
      { name: "倉庫代碼", label: "倉庫代碼", type: "select", refKey: "warehouse", required: true },
      { name: "退回數量", label: "退回數量", type: "number", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
  },

  // ---- MM 採購模組 ----
  "purchase-order": {
    headerTable: "廠商採購主檔",
    headerPk: ["採購編號"],
    headerFields: [
      { name: "採購編號", label: "採購編號", type: "text", required: true },
      { name: "採購日期", label: "採購日期", type: "date", required: true },
      { name: "採購組織", label: "採購組織", type: "select", refKey: "purchase-org", required: true },
      { name: "廠商編號", label: "廠商編號", type: "select", refKey: "vendor", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    detailTable: "廠商採購明細",
    detailFk: ["採購編號"],
    itemNoField: "採購項次",
    detailFields: [
      { name: "物料編號", label: "物料編號", type: "select", refKey: "material", required: true },
      { name: "採購數量", label: "採購數量", type: "number", required: true },
      { name: "預定交期", label: "預定交期", type: "date" },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    readonlyDetailFields: [
      { name: "收貨數量", label: "已收貨" },
      { name: "退回數量", label: "已退回" },
    ],
  },
  receiving: {
    headerTable: "採購收貨主檔",
    headerPk: ["收貨編號"],
    headerFields: [
      { name: "收貨編號", label: "收貨編號", type: "text", required: true },
      { name: "收貨日期", label: "收貨日期", type: "date", required: true },
      { name: "採購組織", label: "採購組織", type: "select", refKey: "purchase-org", required: true },
      { name: "廠商編號", label: "廠商編號", type: "select", refKey: "vendor", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    detailTable: "採購收貨明細",
    detailFk: ["收貨編號"],
    itemNoField: "收貨項次",
    detailFields: [
      { name: "採購編號", label: "採購編號", type: "text", required: true },
      { name: "採購項次", label: "採購項次", type: "text", required: true },
      { name: "物料編號", label: "物料編號", type: "select", refKey: "material", required: true },
      { name: "倉庫代碼", label: "倉庫代碼", type: "select", refKey: "warehouse", required: true },
      { name: "收貨數量", label: "收貨數量", type: "number", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    sourceView: { key: "purchase-open", label: "已採未交明細" },
  },
  "receiving-return": {
    headerTable: "收貨退回主檔",
    headerPk: ["退回編號"],
    headerFields: [
      { name: "退回編號", label: "退回編號", type: "text", required: true },
      { name: "退回日期", label: "退回日期", type: "date", required: true },
      { name: "採購組織", label: "採購組織", type: "select", refKey: "purchase-org", required: true },
      { name: "廠商編號", label: "廠商編號", type: "select", refKey: "vendor", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    detailTable: "收貨退回明細",
    detailFk: ["退回編號"],
    itemNoField: "退回項次",
    detailFields: [
      { name: "採購編號", label: "採購編號", type: "text", required: true },
      { name: "採購項次", label: "採購項次", type: "text", required: true },
      { name: "物料編號", label: "物料編號", type: "select", refKey: "material", required: true },
      { name: "倉庫代碼", label: "倉庫代碼", type: "select", refKey: "warehouse", required: true },
      { name: "退回數量", label: "退回數量", type: "number", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
  },

  // ---- IM 庫存模組 ----
  reservation: {
    headerTable: "物料預留主檔",
    headerPk: ["預留編號"],
    headerFields: [
      { name: "預留編號", label: "預留編號", type: "text", required: true },
      { name: "預留日期", label: "預留日期", type: "date", required: true },
      { name: "工廠代碼", label: "工廠代碼", type: "select", refKey: "plant", required: true },
      { name: "物管編號", label: "物管編號", type: "select", refKey: "planning", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    detailTable: "物料預留明細",
    detailFk: ["預留編號"],
    itemNoField: "預留項次",
    detailFields: [
      { name: "物料編號", label: "物料編號", type: "select", refKey: "material", required: true },
      { name: "預留數量", label: "預留數量", type: "number", required: true },
      { name: "預定交期", label: "預定交期", type: "date" },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
  },
  issue: {
    headerTable: "庫存領用主檔",
    headerPk: ["領用編號"],
    headerFields: [
      { name: "領用編號", label: "領用編號", type: "text", required: true },
      { name: "領用日期", label: "領用日期", type: "date", required: true },
      { name: "工廠代碼", label: "工廠代碼", type: "select", refKey: "plant", required: true },
      { name: "物管編號", label: "物管編號", type: "select", refKey: "planning", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    detailTable: "庫存領用明細",
    detailFk: ["領用編號"],
    itemNoField: "領用項次",
    detailFields: [
      { name: "物料編號", label: "物料編號", type: "select", refKey: "material", required: true },
      { name: "倉庫代碼", label: "倉庫代碼", type: "select", refKey: "warehouse", required: true },
      { name: "領用數量", label: "領用數量", type: "number", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
  },
  "return-to-stock": {
    headerTable: "庫存繳庫主檔",
    headerPk: ["繳庫編號"],
    headerFields: [
      { name: "繳庫編號", label: "繳庫編號", type: "text", required: true },
      { name: "繳庫日期", label: "繳庫日期", type: "date", required: true },
      { name: "工廠代碼", label: "工廠代碼", type: "select", refKey: "plant", required: true },
      { name: "物管編號", label: "物管編號", type: "select", refKey: "planning", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    detailTable: "庫存繳庫明細",
    detailFk: ["繳庫編號"],
    itemNoField: "繳庫項次",
    detailFields: [
      { name: "物料編號", label: "物料編號", type: "select", refKey: "material", required: true },
      { name: "倉庫代碼", label: "倉庫代碼", type: "select", refKey: "warehouse", required: true },
      { name: "繳庫數量", label: "繳庫數量", type: "number", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
  },

  // ---- PP 生產模組 ----
  "work-order": {
    headerTable: "生產工單主檔",
    headerPk: ["工單編號"],
    headerFields: [
      { name: "工單編號", label: "工單編號", type: "text", required: true },
      { name: "工單日期", label: "工單日期", type: "date", required: true },
      { name: "工廠代碼", label: "工廠代碼", type: "select", refKey: "plant", required: true },
      { name: "預定完工", label: "預定完工", type: "date" },
      { name: "生產數量", label: "生產數量", type: "number", required: true },
      { name: "物管編號", label: "物管編號", type: "select", refKey: "planning", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    headerReadonlyFields: [{ name: "入庫數量", label: "已入庫" }],
    detailTable: "生產工單明細",
    detailFk: ["工單編號"],
    itemNoField: "工單項次",
    detailFields: [
      { name: "物料編號", label: "物料編號", type: "select", refKey: "material", required: true },
      { name: "應領用量", label: "應領用量", type: "number", required: true },
      { name: "預定領料", label: "預定領料", type: "date" },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    readonlyDetailFields: [{ name: "已領用量", label: "已領用量" }],
  },
  "material-issue": {
    headerTable: "工單領料主檔",
    headerPk: ["領料編號"],
    headerFields: [
      { name: "領料編號", label: "領料編號", type: "text", required: true },
      { name: "領料日期", label: "領料日期", type: "date", required: true },
      { name: "工廠代碼", label: "工廠代碼", type: "select", refKey: "plant", required: true },
      { name: "物管編號", label: "物管編號", type: "select", refKey: "planning", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    detailTable: "工單領料明細",
    detailFk: ["領料編號"],
    itemNoField: "領料項次",
    detailFields: [
      { name: "工單編號", label: "工單編號", type: "text", required: true },
      { name: "物料編號", label: "物料編號", type: "select", refKey: "material", required: true },
      { name: "倉庫代碼", label: "倉庫代碼", type: "select", refKey: "warehouse", required: true },
      { name: "領料數量", label: "領料數量", type: "number", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
  },
  receipt: {
    headerTable: "工單入庫主檔",
    headerPk: ["入庫編號"],
    headerFields: [
      { name: "入庫編號", label: "入庫編號", type: "text", required: true },
      { name: "入庫日期", label: "入庫日期", type: "date", required: true },
      { name: "工廠代碼", label: "工廠代碼", type: "select", refKey: "plant", required: true },
      { name: "物管編號", label: "物管編號", type: "select", refKey: "planning", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
    detailTable: "工單入庫明細",
    detailFk: ["入庫編號"],
    itemNoField: "入庫項次",
    detailFields: [
      { name: "工單編號", label: "工單編號", type: "text", required: true },
      { name: "物料編號", label: "物料編號", type: "select", refKey: "material", required: true },
      { name: "倉庫代碼", label: "倉庫代碼", type: "select", refKey: "warehouse", required: true },
      { name: "入庫數量", label: "入庫數量", type: "number", required: true },
      { name: "備註說明", label: "備註說明", type: "text" },
    ],
  },
};

module.exports = { DOCUMENT_TABLES };
